directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_131  #Ensure that ALB drops HTTP headers
- CKV_AWS_91  #Ensure the ELBv2 (Application/Network) has access logging enabled
- CKV_AWS_2  #Ensure ALB protocol is HTTPS
- CKV_AWS_103  #Ensure that load balancer is using TLS 1.2
- CKV2_AWS_28  #Ensure public facing ALB are protected by WAF
